# Generated by Django 6.0 on 2025-12-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=1000, verbose_name='Краткая биография и описание')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт преподавания (лет)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за час (валюта)')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(related_name='tutors', to='tutors.subject', verbose_name='Преподаваемые предметы')),
            ],
        ),
    ]
