# Generated by Django 6.0.1 on 2026-02-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото профиля'),
        ),
    ]
