# Generated by Django 6.0.1 on 2026-03-04 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='enrollment_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('declined', 'Отклонена')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='enrollment_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Текст'), ('enrollment_request', 'Заявка на обучение')], default='text', max_length=30),
        ),
    ]
