# Generated by Django 6.0.1 on 2026-03-04 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('tutors', '0005_studentgroup_tutorstudentlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tutors.studentgroup'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', False), ('group__isnull', True)), models.Q(('student__isnull', True), ('group__isnull', False)), _connector='OR'), name='lesson_has_exactly_one_target'),
        ),
    ]
